from pathlib import Path
import math
import pandas as pd
import plotly.graph_objects as go
from theme import THEME_COLORS, apply_plotly_theme

ROOT = Path(__file__).resolve().parents[1]
NODES_CSV = ROOT / "data" / "processed_csv" / "network_nodes.csv"
EDGES_CSV = ROOT / "data" / "processed_csv" / "network_edges.csv"

# Color map for magic types used in the network
COLOR_MAP = THEME_COLORS["magic"]
MAGIC_ORDER = ["Bleue", "Verte", "Rouge", "Noire", "Pourpre", "Blanche"]

# Size configuration (tweak these to make nodes larger/smaller)
INVENTOR_BASE_SIZE = 15       # base marker size for inventors
INVENTOR_SIZE_STEP = 8       # additional size per potion owned
POTION_SIZE = 15             # marker size for potion nodes
# Factor (>1) to push potions farther from their inventor after layout
POTION_SPREAD_FACTOR = 6


def build_inventor_magic_network():
    """
    Build the graph showing inventors, potions and magic families.
    The graph is built from the CSV files generated by the scripts/traitement_inventeurs.py script.
    """
    import networkx as nx

    network_nodes = pd.read_csv(NODES_CSV)
    network_edges = pd.read_csv(EDGES_CSV)

    # Create a lookup dictionary for nodes by their ID
    node_lookup_by_id = {row["id"]: row.to_dict() for _, row in network_nodes.iterrows()}

    # Create a lookup dictionary for inventors by their ID
    inventor_ids = [node_id for node_id, node_data in node_lookup_by_id.items() if node_data.get("type") == "inventeur"]
    # Create a lookup dictionary for potions by their ID
    potion_ids = [node_id for node_id, node_data in node_lookup_by_id.items() if node_data.get("type") == "potion"]

    # Create a mapping of potions to their inventors
    potions_by_inventor = {inventor_id: [] for inventor_id in inventor_ids}
    for _, edge_row in network_edges.iterrows():
        source_node_id, target_node_id = edge_row["source"], edge_row["target"]
        # Only consider edges where the source is an inventor and the target is a potion
        if source_node_id in potions_by_inventor and target_node_id in potion_ids:
            potions_by_inventor[source_node_id].append(target_node_id)

    # Count the number of potions for each inventor
    potion_counts_by_inventor = {inventor_id: len(potions_by_inventor.get(inventor_id, [])) for inventor_id in inventor_ids}

    # Build the network graph
    inventor_ids_to_display = inventor_ids
    network_graph = nx.Graph()

    # Add inventor nodes to the graph
    for inventor_id in inventor_ids_to_display:
        inventor_info = node_lookup_by_id[inventor_id]
        network_graph.add_node(
            inventor_id,
            label=inventor_info.get("label"),
            type="inventeur",
            group=inventor_info.get("group") or "Sans lignée",
            primary_magic=inventor_info.get("primary_magic"),
            potions_count=potion_counts_by_inventor.get(inventor_id, 0),
        )

    # Add potion nodes to the graph and connect them to their inventors
    for inventor_id in inventor_ids_to_display:
        for potion_id in potions_by_inventor.get(inventor_id, []):
            if potion_id in node_lookup_by_id:
                network_graph.add_node(
                    potion_id,
                    label=node_lookup_by_id[potion_id].get("label"),
                    type="potion",
                    primary_magic=node_lookup_by_id[potion_id].get("primary_magic"),
                )
                network_graph.add_edge(inventor_id, potion_id, weight=0.8)

    # Add edges between inventors based on shared lineage or magic type
    for index, inventor_a in enumerate(inventor_ids_to_display):
        lineage_a = node_lookup_by_id[inventor_a].get("group") or "Sans lignée"
        magic_a = node_lookup_by_id[inventor_a].get("primary_magic") or "Inconnue"
        for inventor_b in inventor_ids_to_display[index + 1:]:
            lineage_b = node_lookup_by_id[inventor_b].get("group") or "Sans lignée"
            magic_b = node_lookup_by_id[inventor_b].get("primary_magic") or "Inconnue"

            # Add edges with a smaller weight for shared lineage
            if lineage_a == lineage_b and not network_graph.has_edge(inventor_a, inventor_b):
                network_graph.add_edge(inventor_a, inventor_b, weight=0.0008)
            # Add edges with a bigger weight for shared magic type
            if magic_a == magic_b and not network_graph.has_edge(inventor_a, inventor_b):
                network_graph.add_edge(inventor_a, inventor_b, weight=0.005)

    # If the graph is empty, return an empty figure with a message
    if network_graph.number_of_nodes() == 0:
        empty_figure = go.Figure()
        empty_figure.update_layout(title="Aucun noeud à afficher avec ces filtres")
        return apply_plotly_theme(empty_figure)

    # Compute positions for the nodes using a spring layout
    node_count = network_graph.number_of_nodes()
    layout_scale = 0.2 / math.sqrt(node_count) if node_count > 0 else 0.05
    node_positions = nx.spring_layout(network_graph, k=layout_scale, weight='weight', iterations=200, seed=42)

    shrink_factor = 0.8
    for node_key in list(node_positions.keys()):
        node_positions[node_key] = (node_positions[node_key][0] * shrink_factor, node_positions[node_key][1] * shrink_factor)

    try:
        for inventor_id in inventor_ids_to_display:
            inventor_position = node_positions.get(inventor_id)
            if inventor_position is None:
                continue
            for potion_id in potions_by_inventor.get(inventor_id, []):
                if potion_id in node_positions:
                    delta_x = node_positions[potion_id][0] - inventor_position[0]
                    delta_y = node_positions[potion_id][1] - inventor_position[1]
                    if delta_x == 0 and delta_y == 0:
                        delta_x = 0.01
                        delta_y = 0.01
                    node_positions[potion_id] = (
                        inventor_position[0] + delta_x * POTION_SPREAD_FACTOR,
                        inventor_position[1] + delta_y * POTION_SPREAD_FACTOR,
                    )
    except Exception:
        pass

    def normalize_magic_value(value):
        if value is None or pd.isna(value):
            return ''
        return str(value).strip()

    displayed_inventors = [node for node, data in network_graph.nodes(data=True) if data.get('type') == 'inventeur']
    magic_types = [magic for magic in MAGIC_ORDER if any(normalize_magic_value(network_graph.nodes[inventor].get('primary_magic')) == magic for inventor in displayed_inventors)]
    unknown_inventors = [inventor for inventor in displayed_inventors if normalize_magic_value(network_graph.nodes[inventor].get('primary_magic')) == '']

    if unknown_inventors:
        magic_types.append('Inconnu')
    for inventor in displayed_inventors:
        magic = normalize_magic_value(network_graph.nodes[inventor].get('primary_magic'))
        if magic and magic not in magic_types:
            magic_types.append(magic)

    def get_magic_color(magic_name):
        if not magic_name:
            return '#A0AAB8'
        return COLOR_MAP.get(magic_name, '#888888')

    edge_x_values = []
    edge_y_values = []
    for source_node, target_node in network_graph.edges():
        x0, y0 = node_positions[source_node]
        x1, y1 = node_positions[target_node]
        edge_x_values += [x0, x1, None]
        edge_y_values += [y0, y1, None]

    edge_trace = go.Scatter(
        x=edge_x_values,
        y=edge_y_values,
        mode='lines',
        line=dict(color='#4A4E69', width=1),
        hoverinfo='none',
        showlegend=False,
    )

    figure = go.Figure()
    figure.add_trace(edge_trace)

    custom_legend_entries = [
        ('Inventeur', 'markers', dict(color="#1A1829", size=14, line=dict(width=2, color="#E0E6ED"))),
        ('Potion', 'markers', dict(color='#E0E6ED', size=10, line=dict(width=1, color='#1A1829'))),
        ('Relation', 'lines', dict(color='#4A4E69', width=2)),
    ]

    for legend_name, trace_type, style in custom_legend_entries:
        if trace_type == 'markers':
            figure.add_trace(go.Scatter(
                x=[None],
                y=[None],
                mode='markers',
                marker=style,
                name=legend_name,
                showlegend=True,
            ))
        else:
            figure.add_trace(go.Scatter(
                x=[None, None],
                y=[None, None],
                mode='lines',
                line=style,
                name=legend_name,
                showlegend=True,
            ))

    for magic in magic_types:
        x_values, y_values, hover_texts, node_sizes, labels, colors, marker_symbols = [], [], [], [], [], [], []
        for inventor in displayed_inventors:
            inventor_magic = normalize_magic_value(network_graph.nodes[inventor].get('primary_magic'))
            if magic == 'Inconnu':
                include_inventor = inventor_magic == ''
            else:
                include_inventor = inventor_magic == magic
            if not include_inventor:
                continue
            x_coord, y_coord = node_positions[inventor]
            x_values.append(x_coord)
            y_values.append(y_coord)
            label = network_graph.nodes[inventor].get('label')
            lineage_name = network_graph.nodes[inventor].get('group') or 'Sans lignée'
            potion_total = network_graph.nodes[inventor].get('potions_count', 0)
            hover_texts.append(f"{label}<br>Lignée: {lineage_name}<br>#potions: {potion_total}<br>Magie principale: {magic if magic != 'Inconnu' else 'Inconnue'}")
            node_sizes.append(INVENTOR_BASE_SIZE + int(potion_total) * INVENTOR_SIZE_STEP)
            labels.append(label)
            colors.append('#D9D9D9' if magic == 'Inconnu' else get_magic_color(magic))
            marker_symbols.append('diamond' if magic == 'Inconnu' else 'circle')

        if not x_values:
            continue
        figure.add_trace(go.Scatter(
            x=x_values,
            y=y_values,
            mode='markers+text',
            marker=dict(size=node_sizes, color=colors, symbol=marker_symbols, line=dict(width=2, color='#E0E6ED')),
            text=labels,
            textposition='middle center',
            textfont=dict(color='#E0E6ED', size=11, family='Plus Jakarta Sans'),
            hoverinfo='text',
            hovertext=hover_texts,
            name=str(magic),
            legendgroup=str(magic),
        ))

    potion_x_values, potion_y_values, potion_hover_texts, potion_colors = [], [], [], []
    for node_name, node_data in network_graph.nodes(data=True):
        if node_data.get('type') != 'potion':
            continue
        x_coord, y_coord = node_positions[node_name]
        potion_x_values.append(x_coord)
        potion_y_values.append(y_coord)
        potion_hover_texts.append(f"{node_data.get('label')}<br>Type magie potion: {node_data.get('primary_magic')}")
        potion_colors.append(get_magic_color(node_data.get('primary_magic')))

    if potion_x_values:
        figure.add_trace(go.Scatter(
            x=potion_x_values,
            y=potion_y_values,
            mode='markers',
            marker=dict(size=POTION_SIZE, color=potion_colors, line=dict(width=1, color='#1A1829')),
            hoverinfo='text',
            hovertext=potion_hover_texts,
            name='Potions',
            showlegend=False,
        ))

    figure.update_layout(
        title='Réseau centré sur les inventeurs',
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        plot_bgcolor='#1A1829',
        paper_bgcolor='#13111C',
        height=820,
        margin=dict(l=40, r=40, t=80, b=120),
        legend=dict(
            title='Légende',
            orientation='h',
            x=0.5,
            y=-0.15,
            xanchor='center',
            yanchor='top',
            itemsizing='constant',
            font=dict(size=11, color='#E0E6ED'),
        ),
    )
    figure.update_yaxes(scaleanchor='x', scaleratio=1)

    return apply_plotly_theme(figure)


create_network_graph = build_inventor_magic_network


if __name__ == '__main__':
    create_network_graph().show()
